apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beanstalk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: beanstalk
    spec:
      containers:
      - name: beanstalk
        image: hub.platformservices.io/techevo/beanstalk:ibbo

