apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler 
        image: hub.platformservices.io/techevo/crawler:ibbo
        env:
        - name: DEBUG
          value: "true"
